
" ===================================================
d "ARAnalytics", :subspecs => ["Mixpanel", "Segmentio", "HockeyApp"]
" Netrw Directory Listing                                        (netrw v140)
"   /Users/mengchen/.cocoapods/repos/master/MitRegx/0.0.1
"   Sorted by      name
"   Sort sequence: [\/]$,\<core\%(\.\d\+\)\=\>,\.h$,\.c$,\.cpp$,*,\.o$,\.obj$,\.info$,\.swp$,\.bak$,\~$
"   Quick Help: <F1>:help  -:go up dir  D:delete  R:rename  s:sort-by  x:exec
" ============================================================================
../
MitRegx.podspec
